validator: avoid erroring on invalid BMM requests
LayerTwo-Labs/bip300301_enforcer pull request #54
Opened 2024-10-21 06:29 UTC by torkelrogstad

Invalid BMM requests are not an error in our system, and should not stop our syncing progress.

Prior to this commit we would stop syncing at 26313 due to the inclusion of a BMM request that was not accepted by miners:

```
2024-10-21T06:26:22.262496Z ERROR bip300301_enforcer: src/main.rs:185: Failed to connect block: Error handling M8: Cannot include BMM request; not accepted by miners
```

2024-10-21 12:44 UTC, Ash-L2L requested changes

2024-10-21 12:44 UTC, Ash-L2L commented on src/validator/task.rs
> +            // Make sure to NOT propagate this outwards. These errors are not
If we want to distinguish between fatal and nonfatal errors, we should do so using something like https://docs.rs/fatality/latest/fatality/index.html

2024-10-26 09:34 UTC, nchashch commented
#55 seems to be better, because we are solving this problem systematically for all kinds of non-fatal errors, not just BMM errors. And it is better for readability, because you can look at the error enum variant and see if it is marked as `#[fatal]` -- with the approach in this PR you'd have to dig through the actual implementation code to see if an error is fatal or not.

2024-10-26 09:46 UTC, nchashch commented
I'll close this one, then we can decide between #55 and #56.

2024-10-26 09:46 UTC, closed without merging